### PR TITLE
Add grooveshark backend

### PR DESCRIPTION
**Pull request by camilonova**
Adding support for https://github.com/camilonova/mopidy-grooveshark

### CODE REVIEW

**Comment by kingosticks** [comment]
Shame it doesn't have a font awesome icon yet (https://github.com/FortAwesome/Font-Awesome/issues/2844)

**Comment by kingosticks** [comment]
Thanks.

**Comment by camilonova** [comment]
@kingosticks shame is they have a PipedPier icon and not a grooveshark one ;)

I have tried to understand where this icon is shown, can you tell?

**Comment by kingosticks** [comment]
to the left of the track in pretty much all the pages. helps people tell which backend their search result came from, for example.

**Comment by kingosticks** [comment]
And in fact, not just tracks, pretty much anything.

**Comment by camilonova** [comment]
Saw it.

screen shot 2015-04-25 at 11 36 22 am

**Comment by kingosticks** [comment]
But not when you get the tracks from the Browse page (see https://github.com/woutervanwijk/Mopidy-MusicBox-Webclient/issues/99)

**Comment by kingosticks** [comment]
actually, that is complete rubbish (I should have checked), it works perfectly from the Browse page too.

**Comment by kingosticks** [comment]
Grooveshark has since closed down. Might as well remove this now.

**Pull request merged**
